### ISSUE TITLE
1.19 (RC) Incompatibility

### ISSUE THREAD

**Issue by Tursiops-G** [PTOM76/uncraftingtable-fabric#6]
Only states 1.18.x as compatible:

Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'UncraftingTable' (uncraftingtable76) 1.18.2-1.0.1 with any version that is compatible with:
		 - minecraft 1.19-rc.2
Unmet dependency listing:
	 - Mod 'UncraftingTable' (uncraftingtable76) 1.18.2-1.0.1 requires any 1.18.x version of 'Minecraft' (minecraft), but only the wrong version is present: 1.19-rc.2!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

**Comment by Tursiops-G** [comment]
Thanks. Working fine now (1.19 Release) :)
